
@Host = localhost:5555/api
@at = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZW1haWwiOiJhZG1pbjJAc3R0LmNvbSIsImV4cCI6MTcxNDAxNTQ2NiwiaWQiOjksInJvbGUiOiJBRE1JTiJ9.4CZq_VLCk09Dr0ASvTW_cirHUn_EbIPqsXFDYASDi8Y

@rt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZW1haWwiOiJhZG1pbkBzdHQuY29tIiwiZXhwIjoxNzE0OTIyNTQxLCJpZCI6MSwicm9sZSI6IkFETUlOIn0.e6samH8vGZg15tAckvOatHgaADvK0D6dXKy12nocjRE

################################################
#### AUTH ######################################
##################################################
### create user
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "username" : "admin",
  "email" : "admin@stt.com",
  "password" : "passw0rd",
  "isAdmin" : true,
  "role" : "ADMIN"
}

### get users
GET {{baseUrl}}/auth

### get user by Id
GET {{baseUrl}}/auth/7

### user login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email" : "admin@stt.com",
  "password" : "passw0rd"
}

### user logout
POST {{baseUrl}}/auth/logout

### refresh token
POST {{baseUrl}}/auth/refresh