


### TEST API
GET  {{baseUrl}}


### refresh token
POST {{baseUrl}}/auth/refresh

### user login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username" : "daniel@stt.com",
  "password" : "passw0rd"
}
########################################################
############### CATEGORY ###############################
########################################################
### create category
POST {{baseUrl}}/category/
Authorization: Bearer {{token}}
content-type: application/json

{
  "categoryName": "TEST CAT WITH JWT"
}

### get categories
GET {{baseUrl}}/category/
Authorization: Bearer {{token}}

### update categories
PUT {{baseUrl}}/category/6
Authorization: Bearer {{token}}
Content-Type: application/application/json

{
  "categoryName" : "Updated Name"
}

### get category by ID
GET {{baseUrl}}/category/6
Authorization: Bearer {{token}}
### delete category
DELETE {{baseUrl}}/category/39
Authorization: Bearer {{token}}
