@host = http://localhost:5555/api
@at = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZW1haWwiOiJhZG1pbkBzdHQuY29tIiwiZXhwIjoxNzE0MDI5OTI1LCJpZCI6OCwicm9sZSI6IkFETUlOIn0.bjZmHlukpd8yApCnCQP0H5p6hS2FxsQM-z4EjJBfeFM
@rt= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZW1haWwiOiJhZG1pbkBzdHQuY29tIiwiZXhwIjoxNzE0MDMzMzQ1LCJpZCI6OCwicm9sZSI6IkFETUlOIn0.FyKY9YvhZrB9KJEOG92TO1L1R19q_EGFD7QVwmla3vI

GET {{host}}
#### Get products

GET {{host}}/product
Authorization: Bearer {{rt}}

#### Get product by Id
GET {{host}}/product/P001
Authorization: Bearer {{rt}}

### Create a product
POST {{host}}/product
Authorization: Bearer {{rt}}
Content-Type: application/json

{
    "id" : "P006",
    "productName": "PVC 4INCH, SOGO, CLASS 8.5",
    "categoryId": 3,
    "uom": "EACH",
    "BuyPrice": 7800,
    "SellPriceLevel1": 8300,
    "SellPriceLevel2": 8000,
    "reorderlvl": 10,
    "qtyOhHand": 50,
    "brand": "SOGO",
    "isActive": true
}


### Delete product
DELETE {{host}}/product/P005
Authorization: Bearer {{rt}}
#### Update product
PUT {{host}}/product/P005
Authorization: Bearer {{rt}}
Content-Type: application/json

{
   "productName": "PVC 4INCH, SOGO, CLASS 8.5",
    "categoryId": 3,
    "uom": "EACH",
    "BuyPrice": 7800,
    "SellPriceLevel1": 12000,
    "SellPriceLevel2": 8000,
    "reorderlvl": 10,
    "qtyOhHand": 50,
    "brand": "SOGO",
    "isActive": true
}

### Increae inventory value to P001
POST {{host}}/inventory/increase
Authorization: Bearer {{rt}}
Content-Type: application/json

{
    "inQty": 1,
    "outQty": 0,
    "productId": "P001",
    "remark": "increase 3 to product id P001"
}