

GET {{baseUrl}}
#### Get products

GET {{baseUrl}}/product
Authorization: Bearer {{token}}

#### Get product by Id
GET {{baseUrl}}/product/P001
Authorization: Bearer {{token}}

### Create a product
POST {{baseUrl}}/product
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id" : "P006",
    "productName": "PVC 4INCH, SOGO, CLASS 8.5",
    "categoryId": 3,
    "uom": "EACH",
    "BuyPrice": 7800,
    "SellPriceLevel1": 8300,
    "SellPriceLevel2": 8000,
    "reorderlvl": 10,
    "qtyOhHand": 50,
    "brand": "SOGO",
    "isActive": true
}


### Delete product
DELETE {{baseUrl}}/product/P005
Authorization: Bearer {{token}}
#### Update product
PUT {{baseUrl}}/product/P005
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "productName": "PVC 4INCH, SOGO, CLASS 8.5",
    "categoryId": 3,
    "uom": "EACH",
    "BuyPrice": 7800,
    "SellPriceLevel1": 12000,
    "SellPriceLevel2": 8000,
    "reorderlvl": 10,
    "qtyOhHand": 50,
    "brand": "SOGO",
    "isActive": true
}

### Increae inventory value to P001
POST {{baseUrl}}/inventory/increase
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inQty": 1,
    "outQty": 0,
    "productId": "P001",
    "remark": "increase 3 to product id P001"
}