

GET {{baseUrl}}/purchase

POST {{baseUrl}}/sale
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "SINV004",
  "discount": 600,
  "grandTotal": 69600,
  "total": 69000,
  "customerId": 2,
  "remark": "new sale has been created",
  "saleDate": "may-06-2024",
  "saleDetails": [
    {
      "productId": "P001",
      "productName": "Cement 4.25 CROWN UPDATED",
      "qty": 2,
      "price": 8300,
      "total": 17600,
      "saleId": "SINV004"
    },
    {
      "productId": "P002",
      "productName": "ToiletBowl MATO big",
      "qty": 1,
      "price": 31000,
      "total": 31000,
      "saleId": "SINV004"
    },
    {
      "productId": "P003",
      "productName": "PVC 4Inch Class 8.5 SOGO",
      "qty": 1,
      "price": 21000,
      "total": 21000,
      "saleId": "SINV004"
    }
  ]
}

