
### test
GET http://localhost:5555/

### create category
POST http://localhost:5555/category/
content-type: application/json

{
  "categoryName": ""
}

### get categories
GET http://localhost:5555/category/

### get category by ID
GET http://localhost:5555/category/6