
@Host = localhost:5555/api


### TEST API
GET http://{{Host}}

#### CATEGORY
### create category
POST http://{{Host}}/category/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZW1haWwiOiJkYW5pZWxAc3R0LmNvbSIsImV4cCI6MTcxMzcwNTg0NiwiaWQiOjF9.eRfWizIhxTtoFa4843Yu3nlbxJL1x3ta7S1pYUH3hcw
content-type: application/json

{
  "categoryName": "TEST CAT WITH JWT"
}

### get categories
GET http://{{Host}}/category/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZW1haWwiOiJkYW5pZWxAc3R0LmNvbSIsImV4cCI6MTcxMzcwNTg0NiwiaWQiOjF9.eRfWizIhxTtoFa4843Yu3nlbxJL1x3ta7S1pYUH3hcw

### get category by ID
GET http://{{Host}}/category/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZW1haWwiOiJkYW5pZWxAc3R0LmNvbSIsImV4cCI6MTcxMzcwNTg0NiwiaWQiOjF9.eRfWizIhxTtoFa4843Yu3nlbxJL1x3ta7S1pYUH3hcw


#### USER
### create user
POST http://{{Host}}/user
Content-Type: application/json

{
  "username" : "daniel",
  "email" : "daniel@stt.com",
  "password" : "passw0rd"
}

### get users
GET http://{{Host}}/user

### get user by Id
GET http://{{Host}}/user/3

### user login
POST http://{{Host}}/user/login
Content-Type: application/json

{
  "username" : "daniel@stt.com",
  "password" : "passw0rd"
}